### ISSUE TITLE
Not accepting item links

### ISSUE THREAD

**Issue by Kurudede** [BeepIsla/csgo-nametag-tool#1]
Got to the stage where u insert your item link, Tryied it, but it doesnt accept it. Used both my pernament and community ids and on multiple items.

Thanks in advance and keep up the good work!

**Comment by BeepIsla** [comment]
Can you post the exact link you are inputting?

**Comment by Kurudede** [comment]
https://steamcommunity.com/id/Kurudede/inventory/#730_2_23883178068

Also i tryied this same without https:, and tryied chaging the 'Kurudede' to the pernament steam number

**Comment by Kurudede** [comment]
https://steamcommunity.com/id/Kurudede/inventory/#730_2_23883178068

Tryied without https: , and tryied to change 'Kurudede' to the pernament steam number.

Sorry for closing, it was a missclick

**Comment by BeepIsla** [comment]
Thanks, I will take a look in a bit

**Comment by BeepIsla** [comment]
Weird. It works for me, how are you running this? Powershell? Command Prompt? Something else? Maybe it is causing issues

**Comment by Kurudede** [comment]
I am running Git cmd

**Comment by BeepIsla** [comment]
Weird, it works fine for me. I still changed something in the code, maybe it works now? Try downloading it again.

The only part it now cares about is `730_2_<anynumber>`, anything else does not matter so it should work fine?

**Comment by Kurudede** [comment]
Its fixed now, no idea what i did wrong first time. Thanks!
