### ISSUE TITLE
Encounter Conundrum When Typing "node index.js"

### ISSUE THREAD

**Issue by gatterkwok** [BeepIsla/csgo-nametag-tool#10]
![@3XL9C}EWA9W6R@@X )ZB~R](https://user-images.githubusercontent.com/72333716/211179683-b651afa6-626e-4a50-a61b-f829c32f6778.png)

I am wondering how to get out of this deep trouble... have already been encountering this for days and still no any recuperation occurring.
I would greatly appreciate it if I could have your assistance.
Thank you!

btw, I've tried re-installed or updated Git and Node.js, and I ensure that node-gyp and build tools have been appropriately installed.

**Comment by BeepIsla** [comment]
I did not see this, sorry! Can you access these links directly?

https://raw.githubusercontent.com/SteamDatabase/GameTracking-CSGO/master/csgo/scripts/items/items_game.txt

https://raw.githubusercontent.com/SteamDatabase/GameTracking-CSGO/master/csgo/resource/csgo_english.txt

**Comment by gatterkwok** [comment]
> I did not see this, sorry! Can you access these links directly?
> 
> https://raw.githubusercontent.com/SteamDatabase/GameTracking-CSGO/master/csgo/scripts/items/items_game.txt
> 
> https://raw.githubusercontent.com/SteamDatabase/GameTracking-CSGO/master/csgo/resource/csgo_english.txt

Never mind!
Oops... It seems that i cannot directly access these links, but I can access them with proxy (VPN) just like I am using it to access GitHub to write this comment.
Is there any possible solution? For example, make proxy usable for Node.js, and I've already had Git proxy, but after much Googling, I still cannot find measures to have Node.js proxy.
Thank you!

**Comment by BeepIsla** [comment]
Can you enable your VPN for your entire computer or is it only for your internet browser? You should be able to enable your VPN and then run `node index.js`, it should work then.

**Comment by gatterkwok** [comment]
![image](https://user-images.githubusercontent.com/72333716/214277571-b412ac73-0fa5-4ad1-875e-af3c11e2aac5.png)

I finally make it today,
Thank you so much!

「噫嘻悲哉！此秋聲也，胡為乎來哉！」——歐陽修《秋聲賦》
![image](https://user-images.githubusercontent.com/72333716/214278119-8868b447-834f-4c6b-aa42-4b3900fcf9a0.png)
