### ISSUE TITLE
Problem when running node index.js

### ISSUE THREAD

**Issue by FzyyGit** [BeepIsla/csgo-nametag-tool#11]
![image](https://user-images.githubusercontent.com/128854492/227637236-b9baf736-4e49-4714-b721-288ff05fa118.png)

Been trying to change the name of my m4 using this, but this happens every time I try to run it.

**Comment by BeepIsla** [comment]
Update your NodeJS version

**Comment by FzyyGit** [comment]
That worked, thanks!
