### ISSUE TITLE
Syntax Error when starting

### ISSUE THREAD

**Issue by ModernModers1** [BeepIsla/csgo-nametag-tool#13]
When I type in "node index.js", this happens. I've tried with both 17.x and 20.x versions of nodejs. Tried on 2 different computers (fresh install of programs on 2nd). Pic is from the 2nd PC, the 1st PC had a lower version of nodeJS (it was working a few weeks ago), so I updated nodeJS (didn't work), installed to a different location, then tried a fresh install on another PC, following the tutorial you provided- to no avail.
Love you brother <3

![Untitled](https://github.com/BeepIsla/csgo-nametag-tool/assets/143301183/0fe4dcda-5c12-4adb-96da-61eddef1a386)

**Comment by BeepIsla** [comment]
Yeah, this is because the item data and translations were fetched from the [SteamDatabase/GameTracking-CSGO](https://github.com/SteamDatabase/GameTracking-CSGO/) repository and they recently removed all CSGO things and the file structure for CS2 is different. I will fix it later today.

**Comment by BeepIsla** [comment]
Should now be fixed, try it out to make sure

**Comment by modernmoders** [comment]
It works, you are a god among mortals. <3

**Comment by BeepIsla** [comment]
enjoy, np
