### ISSUE TITLE
`protobufs/csgo/base_gcmessages.proto` not found

### ISSUE THREAD

**Issue by justDeeevin** [BeepIsla/csgo-nametag-tool#15]
When attempting to run the script after following the instructions, I'm presented with an `ENOENT` error, occurring at `index.js:9:41`

![image](https://github.com/BeepIsla/csgo-nametag-tool/assets/90054389/b2d706b2-8d41-43f4-92f0-6a8050bb105c)

**Comment by BeepIsla** [comment]
You are missing the `protobufs` directory, likely because you downloaded the ZIP instead of downloading `git` or you forgot `--recursive` in the `git` options

**Comment by justDeeevin** [comment]
You're right, i just cloned the repo with `gh repo clone`, overlooking the `--recursive` flag. I don't have access to my machine right now but I'll let you know if that's all that i need to change (it probably is)

**Comment by justDeeevin** [comment]
Forgot to get back to this - this fixed the problem! thanks :)
