### ISSUE TITLE
Unable to connect to CSGO backend after new stickers update (08/02/24)

### ISSUE THREAD

**Issue by Author50CO** [BeepIsla/csgo-nametag-tool#16]
![error](https://github.com/BeepIsla/csgo-nametag-tool/assets/99240505/0f333328-358e-45f6-ab99-4de92beac980)

It was working before the patch (tried it out 2 weeks ago)
since the patch its hardstuck without error msg
have noticed that it launched CS2 on the account that it logged in, but nothing happens afterwards.

thankss!111!!

**Comment by BeepIsla** [comment]
Should be fixed now, update and try again

**Comment by Author50CO** [comment]
No good, still not working in the same way.

**Comment by BeepIsla** [comment]
Then I will need a bit and investigate whats wrong

**Comment by Author50CO** [comment]
It's giving me "VAC cannot verify game session cs2" error when i try to matchmake after attempting using your updated code.

**Comment by BeepIsla** [comment]
It just takes a bit to fix itself. There isn't anything you or I can do, its recommended to close Steam while running the tool.

**Comment by Author50CO** [comment]
Completely restarting my PC fixed the VAC game verify issue, idk it has to do anything with it or not but putting it here just so it might help others.

**Comment by BeepIsla** [comment]
Now it should be fixed

**Comment by Author50CO** [comment]
works! Thanks!!!!!!!! <3<3<3<3<3<3<3<3<3
