### ISSUE TITLE
No nametags

### ISSUE THREAD

**Issue by Kurudede** [BeepIsla/csgo-nametag-tool#2]
Hi, the code does register my nametags in inventory but when it comes to using them it says I have none:
![Capthgjsdfaklure](https://user-images.githubusercontent.com/80172688/141444505-01071331-fe16-4652-bd1e-165b709d0454.PNG)

**Comment by BeepIsla** [comment]
Oh, I see the issue. Sorry, I never actually tested it with a name tag so this slipped through. Should be fixed now!
