### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by everlyy** [BeepIsla/csgo-nametag-tool#3]
When i run `node index.js` I get the following error:
```
file:///home/florian/Downloads/csgo-nametag-tool/index.js:54
let { username, password } = await inquirer.prompt([
                             ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

I followed the instructions in the README 

`node -v` gives me: `v12.21.0`

**Comment by BeepIsla** [comment]
[Update NodeJS](https://nodejs.org/) to anything above 14

**Comment by everlyy** [comment]
> [Update NodeJS](https://nodejs.org/) to anything above 14

yea, that worked. thank you!
