### ISSUE TITLE
Is this safe to use?

### ISSUE THREAD

**Issue by O-L-S-N** [BeepIsla/csgo-nametag-tool#4]

**Comment by BeepIsla** [comment]
All this does is send some data to the CSGO backend telling it you are renaming one of your items. That's it. So its definitely VAC safe, Valve could always decide to manually ban people for using special characters in their item names but that would be stupid. I think the worst thing that could happen is simply Valve fixing it and you essentially wasted the price of a name tag.

Its just a visual glitch, nothing big or advantage gaining, there is no reason for Valve to ban people for doing it.

**Comment by setholsson** [comment]
> 

So from the Valve point of view (aka from a server-sided point of view) it will look just like somebody renaming an item normally?

**Comment by BeepIsla** [comment]
Yes

**Comment by setholsson** [comment]
Alright, thanks for the fast replies.
