### ISSUE TITLE
Can't download protobufs files

### ISSUE THREAD

**Issue by Okami9tasin** [BeepIsla/csgo-nametag-tool#5]
Error: ENOENT: no such file or directory, open 'C:/Users/---/csgo-nametag-tool/protobufs/csgo/base_gcmessages.proto'

**Comment by BeepIsla** [comment]
Did you follow the instructions properly and used `git clone https://github.com/BeepIsla/csgo-nametag-tool.git --recursive`? Make 100% sure you have `--recursive` at the end. Also make sure your `git --version` shows somewhere around 2.35.X

**Comment by Okami9tasin** [comment]
Thank you so much for fast responce. Intalling new version of GIT fixed my issue.
