### ISSUE TITLE
How can one achieve this?

### ISSUE THREAD

**Issue by LeonBastian** [BeepIsla/csgo-nametag-tool#6]
Thank you for writing the script and making it public - I wonder how it is possible to get this result 
![image](https://user-images.githubusercontent.com/69186807/154516410-607c9d3e-dcf0-4a66-804f-740d472e6634.png)

**Comment by BeepIsla** [comment]
I assume just use a bunch of new lines using `E280A9` repeatedly something like `0xE280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9` and so on, this is hard to actually test in-game because renaming the item costs money each time

**Comment by LeonBastian** [comment]
Ok, thank you - I will check later if it is possible :)

**Comment by LeonBastian** [comment]
He's using another resolution and the long arabic char - doesn't work on all resolutions / ratio. Thanks again for your suggestion :)
