### ISSUE TITLE
How Exactly do the linebreaks work?

### ISSUE THREAD

**Issue by Pr3roxDLC** [BeepIsla/csgo-nametag-tool#7]
Ive been playing arround with this now and tried to rename a storage unit to this little ascii art (is this even possible): 
```
   ..eeeee..
 e8"   8   "8e
d8     8     8b
8!   .dWb.   !8
Y8 .e* 8 *e. 8P
 *8*   8   *8*
   **ee8ee**
```
Just converting this using the converter from the readme doesnt work, im guessing it doesnt add the linebreaks, so ive tried adding the **E280A9** bytes to the end of each line, however this didnt change the outcome, ive also tried converting the bytes back to ascii resulting in this chars: `â©` and adding them to the end of each line in the ascii art but this also didnt work. Im stuck right now and dont know how i would achieve this ascii art as a name, could someone help me?

**Comment by BeepIsla** [comment]
Does [the example](https://github.com/BeepIsla/csgo-nametag-tool#details) work?

**Comment by Pr3roxDLC** [comment]
yes, the example works, on both the storage unit and an item

**Comment by Pr3roxDLC** [comment]
Here is the [link](https://steamcommunity.com/id/TimTM4/inventory/) to my inventory, it doesnt seem to add the same characters used as linebreaks to the end of the lines on the storage unit

**Comment by Pr3roxDLC** [comment]
I have been looking at the result a bit more and it seems like it would, ontop of not using the linebreaks correctly also collapse any whitespaces as the name the storage unit got is: `"- ..eeeee.. e8" 8"`

**Comment by Pr3roxDLC** [comment]
okay it seems like there is a rly short character limit, ive tried using this **0xE280A9E280A95F5F5F2E2E65656565652E2EE280A95F6538225F5F5F385F5F5F223865E280A964385F5F5F5F5F385F5F5F5F5F3862E280A938215F5F5F2E6457622E5F5F5F2138E280A959385F2E652A5F385F2A652E5F3850E280A95F2A382A5F5F5F385F5F5F2A382AE280A95F5F5F2A2A65653865652A2A** which is the ascii art from my original comment, with spaces replaced by underscores to prevent whitespace collapsing and the "magic bytes" for the linebreaks at the end of each line, this actually works for splitting the text into multiple lines, but it gets cut off like this: `Name Tag: "  ___..eeeee.. _e8"__"`

**Comment by BeepIsla** [comment]
I have updated things, hex input is no more and instead you'd directly write to a file + it now has a warning if the input is too long. That should solve your problem (If you even care anymore idk)
