### ISSUE TITLE
Is this tool still working on the recent version of CS:GO?

### ISSUE THREAD

**Issue by gatterkwok** [BeepIsla/csgo-nametag-tool#8]

**Comment by BeepIsla** [comment]
I don't know, it should work but I have not used it in a long time.

**Comment by gatterkwok** [comment]
I've been testing for the workability on the recent version of CS:GO for a long while, but every attempt turned out that the result was not what I expected.
For instance, I was attempting changing the name of my Storage Unit to
> ❝
> ✎𝕰𝖓𝖈𝖞𝖈𝖑𝖔𝖕𝖆𝖊𝖉𝖎𝖘𝖒
> ☭ 𝕴𝖘
> ♚𝕰𝖒𝖇𝖔𝖚𝖗𝖌𝖊𝖔𝖎𝖘𝖊𝖒𝖊𝖓𝖙.
> ❞

But I got merely  "❝✎𝕰𝖓𝖈𝖞𝖈𝖑𝖔𝖕𝖆" for it;
<img width="416" alt="微信截图_20220816151317" src="https://user-images.githubusercontent.com/72333716/184825081-956b9330-c102-4543-823c-d9798b824729.png">
<img width="273" alt="微信截图_20220816151402" src="https://user-images.githubusercontent.com/72333716/184825085-a09b0898-8ef3-449d-b305-1a0dbd0bc065.png">
While I tried putting "Encyclopaedism Is Embourgeoisement", the version without special characters, on it, "Encyclopaedism Is Emb" was the result I got.
<img width="274" alt="微信截图_20220816145828" src="https://user-images.githubusercontent.com/72333716/184825188-1f0e7874-7f29-44a3-ad6d-2c002fd6dd1c.png">
<img width="397" alt="微信截图_20220816145842" src="https://user-images.githubusercontent.com/72333716/184825199-e1d48e78-ef81-4cf6-96ac-ff9122654a9a.png">
These troubled me a lot because the unexpected "Encyclopaedism Is Emb" was exactly what led me to this program. That is,  the barrier of character limitation of the Name Tag was the reason why I would seek for resolution.
<img width="498" alt="limitation" src="https://user-images.githubusercontent.com/72333716/184825665-1b13758a-f3d1-42b1-a67e-639f0b27efcd.png">

English is not my native language, please excuse typing errors.
Thank you for your devotion!

**Comment by BeepIsla** [comment]
Maybe the name is too long or some special characters just don't work? I don't know

**Comment by gatterkwok** [comment]
Plus, by my own experiment costing $1.99 ( frastrated :-( ), [this text to hex converter](https://www.online-toolz.com/tools/text-hex-convertor.php) is much better than [the given one](https://www.rapidtables.com/convert/number/ascii-to-hex.html).

**Comment by gatterkwok** [comment]
> Maybe the name is too long or some special characters just don't work? I don't know

That is, this tool is as well under the character limitation? Oh my...

**Comment by BeepIsla** [comment]
I have tested and I think your text is just too long. The limit is 21 characters

**Comment by BeepIsla** [comment]
I have updated the tool so you no longer have to use a hex converter and can instead directly write into a file.

**Comment by gatterkwok** [comment]
> I have tested and I think your text is just too long. The limit is 21 characters

Oh my... What a lamentable news :-(
And simultaneously, this can be regarded as a perfect answer to the query come up in [Issue #7](https://github.com/BeepIsla/csgo-nametag-tool/issues/7).
In case that more users would become confused about this kind of incomprehensible issues, it would be favourable to append something to do with the restriction to the README.md.

**Comment by BeepIsla** [comment]
The tool now warns you if your input is longer than 21 characters

**Comment by gatterkwok** [comment]
> I have updated the tool so you no longer have to use a hex converter and can instead directly write into a file.

Anyway, thank you very much for your everlasting devotion and conscientiousness!
