### ISSUE TITLE
Name with file?

### ISSUE THREAD

**Issue by AstroBoof** [BeepIsla/csgo-nametag-tool#9]
It says find file new_name.txt and edit it but where is it? I've tried making my own txt file but thats not working either? Without the file method now you can't use the deagle spacers

**Comment by AstroBoof** [comment]
I found the file in C://users/(my name)/csgo-nametag-tool. but you should add where you put it in the prompt

**Comment by AstroBoof** [comment]
Also in the file option codes like this dont work

0xE280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E282BF20E29B8FE280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9
0xE280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E282BF20E29B8FE280A9E280A9E280A9E280A9
0xE280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9E280A9

**Comment by BeepIsla** [comment]
For files you must input then characters directly, you cannot use hexadecimal. If that is not an option for you then you should use [HxD](https://mh-nexus.de/en/hxd/) or a similar program to edit the bytes directly

**Comment by AstroBoof** [comment]
Really? in previous versions you could use hexa to get spacers to heighten the weapons in the ui.

**Comment by BeepIsla** [comment]
Correct, I removed that because it apparently was too complicated for some people and instead it now creates a file you can copy/paste unicode characters into, since new lines don't work they are automatically replaced with `E280A9` internally (Creates a new line on the name tag without the actual new line character)
